### ISSUE TITLE
ASCII tag type is not validated enough

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image-tiff#102]
The specification says the following:

> 2 = ASCII 8-bit byte that contains a 7-bit ASCII code; the last bytemust be NUL (binary zero)

We instead validate that the string is valid UTF-8, a superset of the allowed values

https://github.com/image-rs/image-tiff/blob/679f4f075ba653a29de394e4c6413f94d2933b9c/src/decoder/ifd.rs#L478-L480

This may not seem problematic at first glance but callers might assume that the string can be sliced at any byte. This would panic at runtime if the index turned out not to be a utf-8 character boundary. If values were validated to be truly ascii then all byte boundaries are valid character boundaries.

**Comment by emmanuelantony2000** [comment]
We could check if the buffer contains all valid ascii values using the `is_ascii` function.
Then we could convert it to an `&str` and then trim it. Correct me if I am wrong.
Would this solve this issue? I would be happy to give a PR.

**Comment by HeroicKatora** [comment]
There are two checks that would need to be adjusted. You mentioned the first, all values should be checked against `is_ascii`. Additionally, the current implementation will _optionally_ remove the final NUL-byte but it should _require_ at least one such byte to exist before it is trimmed. Your approach sounds fine, I'd be glad to review a PR for this :)
