### ISSUE TITLE
Increase size constraints

### ISSUE THREAD

**Issue by ruffson** [image-rs/image-tiff#105]
The current size constraints of TIFF images (e.g. the size of `decoding_buffer_size`) should be increased.

I am working with TIFF files which are mostly between 150 and 300MiB. I think it is fair to assume that most others who deal with TIFF images also deal with larger images.

(In general I would argue that the library should not have any such restriction at all (at least below the max possible limit). And that these checks should be made by clients who use this library.)

But for now I propse two possible solutions for now:

1. Either increase the size limit to 512MiB, which should be reasonable for most hardware in 2020 OR
2. Make this limit configurable when initializing the decoder.

**Comment by HeroicKatora** [comment]
It [is configurable](https://docs.rs/tiff/0.6.0/tiff/decoder/struct.Decoder.html#method.with_limits). The limit shouldn't be enforced until actual use so the fact that this method can only be called after the initial ifd is read shouldn't matter too much for your use case.

**Comment by ruffson** [comment]
> It [is configurable](https://docs.rs/tiff/0.6.0/tiff/decoder/struct.Decoder.html#method.with_limits). The limit shouldn't be enforced until actual use so the fact that this method can only be called after the initial ifd is read shouldn't matter too much for your use case. Did you expect a different way of configuring?

Oh damn, sorry I have overlooked that! I take back everything then :)
