### ISSUE TITLE
"Inconsistent sizes" when parsing LZW compressed images

### ISSUE THREAD

**Issue by ruffson** [image-rs/image-tiff#106]
With _some_ LZW compressed TIFF images, I am getting a `Format error: Inconsistent sizes encountered.` in the `expand_strip(...)` method of `decoder/mod.rs`.

I uploaded 3 example files that show this problem [here](https://cloud.xeres.org/s/QX9z3F5Me8E5RGE) (~630MB).

Last time when I tried to debug this the only thing I noticed is that in the `LZW::new(...)` the `uncompressed.len()` is larger than the buffer size. And iirc the `len()` was the image' width or length.

Anyways, for the three images I printed the `bytes`, `buffer.byte_length()` and the `max_uncompressed_length` right before the error is returned in `expand_strip(...)`:

#### `crater1_lzw.tif`:
bytes: `23714`, buffer_len: `1,` max_uncompressed_length: `23710`
#### `crater2_lzw.tif`
bytes: `23714`, buffer_len: `1`, max_uncompressed_length: `23710`
#### `geotiff2.tif`
bytes: `7710`, buffer_len: `1`, max_uncompressed_length: `2570`

About the images: The first two are from the [CTX data](http://murray-lab.caltech.edu/CTX/index.html) from the Mars Reconnaissance Orbiter. They _should_ be public domain but I am not 100% sure. 
The `geotif2.tif` is taken from the sample files of the [geotiff library](https://github.com/OSGeo/libgeotiff) (and as far as I can tell the official geotiff organization) [here](http://download.osgeo.org/geotiff/samples/gdal_eg/).

One last thing about these samples, if you think that these provide perfect examples of geotiff, check their [readme](http://download.osgeo.org/geotiff/samples/README), specifically: "Just because a file is in this tree does not imply that it follows the standard correctly [...]"

**Comment by mntns** [comment]
I'm facing the same error in `expand_strip()` when trying to load large LZW-compressed images. As already mentioned on gitter, it appears to be a regression from 0.5.0 to 0.6.0. My debugging so far only resulted in locating it in `expand_strip()`, as @ruffson already wrote, but [here is another example image](https://images.wallpen.com/image_tiff_lzw_example.tif) that fails to load with `InconsistentSizesEncountered` (also ~630MB, but a single image).
