### ISSUE TITLE
Reset values of tags on "next_image"?

### ISSUE THREAD

**Issue by Christopher22** [image-rs/image-tiff#142]
Currently, the values of the tags "Compression", "SamplesPerPixel" and "SampleFormat" are not reset to the default values specified in the TIFF specification [when "next_image" is called](https://github.com/image-rs/image-tiff/blob/153ed48ee7e06ac3018f8156ed64a956edfba8c6/src/decoder/mod.rs#L671).

Is that "persistance across pages" correct? Unfortunately, I am not an expert in the TIFF format. However, one might have to least document it because it could quickly lead to strange errors. I'm willing to contribute a pull request.

**Comment by fintelia** [comment]
Good catch! If there is no clear guidance in the spec, the right thing to do is probably to go through the libtiff source code to see how they handle this case

**Comment by HeroicKatora** [comment]
I'm decently sure that persistence across pages is incorrect although it doesn't say so outright. But the spec calls each IFD an individual 'subfile' which implies disjoint semantics to me. It also discourages writers from producing files wherein two IFD entries point to the same data. In other words I would reset it but consult with libtiff in any case which fully deletes and re-initializes the directory whenever a new one is read.

> https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_dirread.c#L3632-3634

**Comment by Christopher22** [comment]
Sorry for the delay - quite busy times... 
I created a fix to reset the tags to their default values if not otherwise specified. I would now consider it "expected behavior".

**Comment by HeroicKatora** [comment]
This should be solved as published in `0.7.1`.
