### ISSUE TITLE
Support for arbitrary sample counts

### ISSUE THREAD

**Issue by Masterchef365** [image-rs/image-tiff#147]
For my use-case, I need to decode TIFFs which contain 20+ channels. Currently, image-tiff only supports specific `ColorType`s, although a previous (and slower) version of the crate did support `ColorType::Other`. I have an extremely messy patch at https://github.com/Masterchef365/image-tiff/tree/more_channels which works for my purposes, but other users of this crate might benefit from a more refined approach.

**Comment by raphi-web** [comment]
I would also benefit from this! Would love to see it implemented.
