### ISSUE TITLE
Release with jpeg-dependency 0.2

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image-tiff#156]
Can we get a new release with this, also for `image`? `image` itself is already using `jpeg-decoder 0.2` and this is showing as a duplicate dependency for us.

_Originally posted by @MarijnS95 in https://github.com/image-rs/image-tiff/issues/155#issuecomment-1046903694_

**Comment by MarijnS95** [comment]
@HeroicKatora Can we get a publish for this?

CC @emilk, according to https://github.com/image-rs/image-tiff/pull/155#issuecomment-1094919107 a patch release is all it takes :)
