### ISSUE TITLE
Unavailable Specification

### ISSUE THREAD

**Issue by luksab** [image-rs/image-tiff#179]
The doc-comments for the tiff crate link to the TIFF specification, but as [loc.gov](https://www.loc.gov/preservation/digital/formats/fdd/fdd000022.shtml) notes, this link is unavailable since mid-2017.
The specification has been archived by archive.org [there](https://web.archive.org/web/20210108073850/https://www.adobe.io/open/standards/TIFF.html) and is available in several other locations listed by [loc.gov](https://www.loc.gov/preservation/digital/formats/fdd/fdd000022.shtml#specs).

**Comment by luksab** [comment]
Should the archive.org link or one of the mirrors be linked to in the doc-comments?
Once that is decided, I could make a PR changing the doc-comment.

**Comment by HeroicKatora** [comment]
Archive seems like a very stable, long-term solution. I'd prefer that over another soon-to-be-outdated link.
