### ISSUE TITLE
16-bit-per-channel images using PackBits compression fail to load correctly.

### ISSUE THREAD

**Issue by cessen** [image-rs/image-tiff#192]
- Crate version: tiff 0.8.0
- Rust version: 1.65.0
- Platform: Linux x86-64

I have a bunch of images that I'm trying to load via `tiff`.  They're extremely boring images: they're all pretty much black, but with a little bit of sensor noise from the camera (we use them for noise calibration).  They were all extracted from a 12-bit video file via ffmpeg, and all of the images are RGB, 16-bits-per-channel, and use PackBits compression.

Depending on the particular frame, `tiff` either:

1. Fails to load the file at all.
2. Loads it successfully, but produces an obviously corrupted image.

Some example files (warning: about 50MB each):

1. Loads but corrupted: [0001.tiff](https://perm.cessen.com/2022/tiff_bug/0001.tiff)
2. Fails to load at all: [0007.tiff](https://perm.cessen.com/2022/tiff_bug/0007.tiff)

A scaled-down screenshot of the corrupted load from 0001.tiff:

![](https://perm.cessen.com/2022/tiff_bug/0001_loaded.jpg)

Note that it should look basically black (or rather, a very dark gray).  And it loads correctly in my system's image viewing software as well as Gimp.

By re-exporting from Gimp with either LZW compression or no compression, I was able to get both 0001.tiff and 0007.tiff to load correctly with `tiff` (no corruption).  However, re-exporting from Gimp with PackBits still results in corruption when loaded by `tiff`, though the corruption is little different and both files load:

![](https://perm.cessen.com/2022/tiff_bug/0007_gimp_loaded.jpg)

My initial thought was that I was somehow misusing the 16-bit buffer that `tiff` returns.  But since my code works correctly with LZW and non-compressed 16-bit images, I don't *think* that's what's going on.

**Comment by astraw** [comment]
Both these files seem to read fine with tiff 0.8.0. I compare the printed output of my program (below) with that shown in FIJI when I hover over a pixel. I have specifically looked at first few pixels of 0001.tiff. Also with rustc 1.65.0, this time on macOS (stable-aarch64-apple-darwin).

```rust
use anyhow::Result;
use std::io::Cursor;

use tiff::decoder::DecodingResult;

fn main() -> Result<()> {
    for fname in ["0001.tiff", "0007.tiff"] {
        let file_data = std::fs::read(fname)?;
        let mut decoder = tiff::decoder::Decoder::new(Cursor::new(file_data))?;
        let buf = decoder.read_image()?;
        let color = decoder.colortype()?;

        let (width, height) = decoder.dimensions()?;

        match (color, buf) {
            (tiff::ColorType::RGB(16), DecodingResult::U16(image_data)) => {
                let expected_size = width * height * 3;
                if image_data.len() != expected_size as usize {
                    anyhow::bail!("actual image size different than expected");
                }
                let stride = width * 3;

                if image_data.len() != expected_size as usize {
                    anyhow::bail!("actual image size different than expected");
                }

                println!("{fname}");
                for image_row in image_data.chunks_exact(stride as usize).take(10) {
                    for pixel in image_row.chunks_exact(3).take(10) {
                        print!("{:?}", pixel);
                    }
                    println!("");
                }
            }
            _ => {
                anyhow::bail!("unsupported tiff type");
            }
        }
    }
    Ok(())
}
```

**Comment by HeroicKatora** [comment]
Got it. There's a read that assumes to succeed for the full width but instead doesn't. This desyncs the decoder (a bunch of pixels are zeroed, and then literal data is interpreted as a header).

**Comment by cessen** [comment]
Thanks so much!

**Comment by cessen** [comment]
Confirmed fixed in my usage of `tiff` as well.  Thanks again!
