### ISSUE TITLE
Reading a larger tiff with PackBits fails if original reader is a bufreader, but worked in 0.7.1

### ISSUE THREAD

**Issue by ChrisRega** [image-rs/image-tiff#194]
Hello!
## History
We are using image-rs to load and validate tiff files produced by an internal software (C++ with libtiff for writing). Until 0.7.1 we could just read those without an issue. Since then and up to 0.8.0 we run into:
`IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })`.

## Our debugging
So we debugged into this, originally coming from the image crate and found that it wraps the reader into a bufreader before trying to decode the tiff.
So I added a unit-test to reproduce the issue inside image-tiff which looks like:

```rust
#[test]
fn vgsm_tiff_large_rgb_packbits_fails() {
    let path = PathBuf::from(TEST_IMAGE_DIR).join("screenshot.tif");
    let mut decoder =
        Decoder::new(BufReader::new(File::open(path).expect("Cannot find test image!"))).unwrap();

    let mut img_res = decoder.read_image().unwrap();
}

#[test]
fn vgsm_tiff_large_rgb_packbits_passes() {
    let path = PathBuf::from(TEST_IMAGE_DIR).join("screenshot.tif");
    let mut decoder =
        Decoder::new(File::open(path).expect("Cannot find test image!")).unwrap();

    let mut img_res = decoder.read_image().unwrap();
}
```

While trying to create a minimum example, I also stumbled across the fact, that the image has to be of significant size (35x20px did not fail, 1920x1280 fails). After some chunks (with the attached image its in chunk 6), the `PackBitsReader` tries to read the header with `self.reader.read_exact(&mut header)?;` (stream.rs line ~370) and fails out.
Chunk offsets look identical between the readers

## File for reproduction
Tiff-file is attached gzipped:
[screenshot.tif.gz](https://github.com/image-rs/image-tiff/files/10166953/screenshot.tif.gz)

Snipped above should reproduce it as unit-test inside decode_images.rs

Any help is greatly appreciated :)
Many thanks in advance for your great work!

**Comment by HeroicKatora** [comment]
Can you check if <https://github.com/image-rs/image-tiff/pull/193> fixes it? If so then the working code is completely incidental and was probably previously only masked by some other details (such as a small image size).

**Comment by ChrisRega** [comment]
Indeed, seems to pass on master! So we'll just patiently wait for a new release. Thanks a lot!
