### ISSUE TITLE
InconsistentSizesEncountered error reading Tiff with planar config

### ISSUE THREAD

**Issue by pka** [image-rs/image-tiff#198]
When reading the attached file with `image::open` I get `Decoding(DecodingError { format: Exact(Tiff), underlying: Some(FormatError(InconsistentSizesEncountered)) })`.

[small_world.tif.gz](https://github.com/image-rs/image-tiff/files/10347258/small_world.tif.gz)

gdalinfo:
```
Driver: GTiff/GeoTIFF
Files: data/tiff/small_world.tif
Size is 400, 200
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-180.000000000000000,90.000000000000000)
Pixel Size = (0.900000000000000,-0.900000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-180.0000000,  90.0000000) (180d 0' 0.00"W, 90d 0' 0.00"N)
Lower Left  (-180.0000000, -90.0000000) (180d 0' 0.00"W, 90d 0' 0.00"S)
Upper Right ( 180.0000000,  90.0000000) (180d 0' 0.00"E, 90d 0' 0.00"N)
Lower Right ( 180.0000000, -90.0000000) (180d 0' 0.00"E, 90d 0' 0.00"S)
Center      (   0.0000000,   0.0000000) (  0d 0' 0.01"E,  0d 0' 0.01"N)
Band 1 Block=400x20 Type=Byte, ColorInterp=Red
Band 2 Block=400x20 Type=Byte, ColorInterp=Green
Band 3 Block=400x20 Type=Byte, ColorInterp=Blue
```

AFAIK the image is in public domain, but if that is important I can convert an existing test image to a similar planar config.

**Comment by fintelia** [comment]
This crate doesn't support planar images at the moment. The specific error you're seeing comes from [a check validating that the image has the expected number of strips](https://github.com/image-rs/image-tiff/blob/289fab2fcdb24a4e9c8a11ffd1066d987a7de971/src/decoder/image.rs#L207-L215) which planar images never will because they store each channel in a different strip. 

We should probably add a check to detect planar images and return a better error message instead.

(If you or someone else wants to add planar image support, I'd be happy to review PRs. However, I'm not sure how much work that would be to implement)

**Comment by pka** [comment]
> The TIFF spec also apparently recommends against planar images:

This recommendation is probably outdated. All my Linux image viewers (using different TIFF libs) support planar images.

In earth observation planar images are very common since many years. They do not only use RGB in different strips (called bands), but all sensors are stored in separate bands and can be combined by the client.

> (If you or someone else wants to add planar image support, I'd be happy to review PRs. However, I'm not sure how much work that would be to implement)

I'll maybe try a basic implementation which at least fixes `Decoder::read_chunk` and returns the first band as result of `Decoder::read_image`.
