### ISSUE TITLE
Decoding an image with missing required tag

### ISSUE THREAD

**Issue by Noxdor** [image-rs/image-tiff#209]
I am trying to read the `datetime` tag from raw ARW images of a sony camera.
Unfortunately, trying to decode the image I am getting an error that the ImageWidth tag is missing.
Is there a way to get around that or am I doing something wrong?

```rust
let img = File::open("raw/DSC00001.ARW").unwrap();

let mut tiff_dec = Decoder::new(img).unwrap(); // this unwrap errors
let datetime = tiff_dec.get_tag(DateTime).unwrap();

println!("datetime: {:?}", datetime);
```

**Comment by fintelia** [comment]
I don't think we currently expose an API to access tags from partially corrupt TIFF files. And from the perspective of this crate, a RAW file basically amounts to a corrupt TIFF...

**Comment by Noxdor** [comment]
@fintelia Okay I understand, I am missing unfortunately some knowledge and experience with this topic, just trying to write a small cli that takes in my raw camera images and spits out a timelaps video, do you have any suggestions on another library that can handle RAW images and extracting the DateTime tag from them? (in my research I only discovered this library that appeared viable to me.)

**Comment by fintelia** [comment]
There doesn't seem to be a ton of documentation on exactly what a ARW file is. Google suggests that it is quite similar to TIFF. So you could try reverse engineering. Fork this crate, try commenting out the failing checks, and see what tags are present in the file. Maybe you'll get lucky and and your files contain a DateTime formatted the same way as TIFF

The other thing to try would be finding a converter program to a standard image format. As long as it preserved the relevant data, you'd be in a much better position to extract it with an existing library

**Comment by Noxdor** [comment]
> There doesn't seem to be a ton of documentation on exactly what a ARW file is. Google suggests that it is quite similar to TIFF. So you could try reverse engineering. Fork this crate, try commenting out the failing checks, and see what tags are present in the file. Maybe you'll get lucky and and your files contain a DateTime formatted the same way as TIFF
> 
> The other thing to try would be finding a converter program to a standard image format. As long as it preserved the relevant data, you'd be in a much better position to extract it with an existing library

Thank you for your time, this reply is really helpful! I really appreciate the help, I will fork and check what I can achieve. It do think that ARW has the datetime tag, because when I run `file DSC00001.ARW` I get the following output:
```
DSC00001.ARW: TIFF image data, little-endian, direntries=19, compression=
JPEG (old), description=                               , manufacturer=SONY, m
odel=ILCE-7RM3, orientation=upper-left, xresolution=290, yresolution=298, res
olutionunit=2, software=ILCE-7RM3 v3.01, datetime=2023:07:20 13:54:37
```

So I guess I should be able to extract it. Anyway, thanks again for the help, all the best!
