### ISSUE TITLE
Better tests

### ISSUE THREAD

**Issue by birktj** [image-rs/image-tiff#24]
I am working on  https://github.com/PistonDevelopers/image/issues/858, but I am not entirely confident that my modified decoder is correct. Some more thorough test that would check if the decoded data is correct would be nice. There should also be tests for things like horizontal predictor.

**Comment by Shnatsel** [comment]
This is actually something fuzzing can help with. Just decode an image with both decoders and compare results. The fuzzer will automatically discover interesting inputs.

https://github.com/Frommi/miniz_oxide has used this approach to verify the Rust translation against the original C implementation. 
I've also used this setup to find memory disclosure vulnerabilities, although I've been comparing two runs of the same function. Here's a nice, minimal example that you can use as a base: 
https://github.com/Shnatsel/lodepng-afl-fuzz-differential
