### ISSUE TITLE
Provide a way to retrieve all tags defined within a file

### ISSUE THREAD

**Issue by gschulze** [image-rs/image-tiff#243]
Currently, it is only possible to retrieve single tags via `get_tag(...)` and `find_tag(...)`. However, one might be interested in obtaining all defined tags, for instance, when modifying the TIFF and writing it to a file again. Two possible APIs come to my mind:
* `fn get_all_tags():  impl<Iterator<Item = Tag>>`, returning all tags defined in the TIFF file, or
* `fn get_all_tags():  HashMap<Tag, ifd::Value>`, returning all tags along with their value

It would be really nice to have this addition.

**Comment by spoutn1k** [comment]
I'm working on #242 to do just that, it is far from ready but I am implementing a newtype over your second proposition to streamline tag access. I can update here once I have a better prototype.
