### ISSUE TITLE
Encoding panics if the input is too short

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-tiff#35]
The following code causes a panic in the encoder:

```rust
let input_data = vec![1,2,3].as_slice();
let mut output = Vec::new();
let mut output_stream = Cursor::new(output);
if let Ok(mut tiff) = TiffEncoder::new(&mut output_stream) {
    tiff.write_image::<colortype::RGB8>(50, 50, &input_data)
}
```
Error message:
`thread 'main' panicked at 'index 7500 out of range for slice of length 173', src/libcore/slice/mod.rs:2349:5`

**Comment by birktj** [comment]
Wouldn't you agree that this is a programmer error and should be allowed to panic? The way I think about it is that it is the programmers job to make sure that enough data is fed to the encoder, just like it is the programmers job to make sure that they stay within the bounds of a vector.

**Comment by Shnatsel** [comment]
According to [Rust Book](https://doc.rust-lang.org/1.31.1/book/ch09-03-to-panic-or-not-to-panic.html) panics should be used only on unrecoverable errors. If encoding one image fails it doesn't mean that the library should unilaterally shut down the entire program. The API client should be allowed to decide if having this image compressed is critical for the execution or not.
