### ISSUE TITLE
Decoding 16-bit gray images

### ISSUE THREAD

**Issue by SonnyX** [image-rs/image-tiff#54]
Somehow the attached image does not decode correctly, it only reads half of the rows width.
[2_1.zip](https://github.com/image-rs/image-tiff/files/3616556/2_1.zip)

**Comment by SonnyX** [comment]
Increasing `max_uncompressed_length` on line `src/decoder/mod.rs:567` fixes the issue.

**Comment by HeroicKatora** [comment]
This is very downstream, the erroneous calculation almost certainly happens sooner. You seem to be on a good path, maybe I can help speed this up.

https://github.com/image-rs/image-tiff/blob/f6a91065d937fac56e2b70dae90da20e40fa46c1/src/decoder/mod.rs#L690

It's where the value for `max_uncompressed_length` comes from and on first glance this seems wrong. The `buffer_size` should involve the actual bit counts in some form however it only has the sample count.

**Comment by SonnyX** [comment]
I also looked into buffer_size at first, thinking it was wrong, however the interesting conclusion that I came to is that it's not actually wrong.
buffer_size is to represent the size of the buffer, since we're dealing with datatype u16 it should be correct that this is only half of the bytes.
It just seems that max_uncompressed_length may need a *2 to deal with the bitdepth.

**Comment by Nimmerwoner** [comment]
I too have 16-bit deflate-compressed tiffs that fail to be read by image-tiff (attached). What can I do to help support it?

[16bitdeflategrayscale.zip](https://github.com/image-rs/image-tiff/files/4332672/16bitdeflategrayscale.zip)

**Comment by vadixidav** [comment]
I am using the [FLIR dataset](https://www.flir.com/oem/adas/adas-dataset-form/) and when I tried to decode their 16-bit TIFF I encountered this error: `failed to read image from TIFF: FormatError(InconsistentSizesEncountered)`.

Anyone know where I should look to get this working?

**Comment by vadixidav** [comment]
I just tried it with `master` and it actually just worked! The newest version of the crate should be published.

**Comment by vadixidav** [comment]
@HeroicKatora @fintelia Could one of you publish a new version? I am not sure what the state of master is, but even a `0.5.0` would be useful for people directly depending on this crate for 16-bit tiffs. A new version can always be released if there are ongoing refactoring changes.

**Comment by HeroicKatora** [comment]
I'll create the release PR today, sorry for the delay.

**Comment by HeroicKatora** [comment]
Upgrade to `0.5` and the decoding should be successful.
