### ISSUE TITLE
`num-derive` dependency worth it?

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image-tiff#57]
The crate currently uses `num-derive` to add some `num-traits::FromPrimitive` implementations to a couple of enumerations. Since this is done via a procmacro it requires sequencing in the compilation pipeline, compiling `proc-macro2`/`syn` prior. All cases are simple enumerations such as :

```rust
pub enum Type {
    BYTE = 1,
    ASCII = 2,
    SHORT = 3,
    LONG = 4,
    RATIONAL = 5,
}
```

The functionality could also be added with a standard macro in such simple cases, see [this example in `smoltcp`](https://github.com/m-labs/smoltcp/blob/master/src/macros.rs#L26-L77) which adds very similar converters for `std::convert::{From, To}`.

**Comment by birktj** [comment]
It is probably not necessary, for example we [already use a macro to create the `Tags` enum](https://github.com/image-rs/image-tiff/blob/master/src/decoder/ifd.rs#L12-L38). A new macro that adds `From` and `To` impls should be fine.

**Comment by Robzz** [comment]
Yeah it's totally droppable. `image` used to depend on it, but only because of the tiff code, and I [removed it from image](https://github.com/image-rs/image/pull/783/files#diff-b4aea3e418ccdb71239b96952d9cddb6) when extracting the code into this crate. It's probably worth doing.

**Comment by HeroicKatora** [comment]
One remaining question is one of style. Either go with the `Unknown(_)` variant from `Tag` or make the conversion return an `Option` like it does right now in the [`FromPrimitive`](https://docs.rs/num-traits/0.2.8/num_traits/cast/trait.FromPrimitive.html#tymethod.from_i64) trait.
