### ISSUE TITLE
JPEG Compression Tag

### ISSUE THREAD

**Issue by powturns** [image-rs/image-tiff#82]
I noticed that `CompressionMethod::JPEG` has the value `6`. According to [wikipedia](https://en.wikipedia.org/wiki/TIFF#TIFF_Compression_Tag), this is actually the "obsolete 'old-style' JPEG" that "... should never be written". For consistency with `Deflate`/`OldDeflate` should we consider renaming this to `OldJPEG`?

I realize this is a breaking change, but since it seems like there is some work being done around this area it may be a good opportunity to standardize the names.

**Comment by HeroicKatora** [comment]
I would just deprecate the old variant. It matches the intended semantics and is not a breaking change.

**Comment by 51systems** [comment]
If we incorporate the modern JPEG (7), would that be called `NewJPEG`?

**Comment by HeroicKatora** [comment]
I prefer the implicit suggestion, `ModernJPEG` :grinning:
