### ISSUE TITLE
Floating point predictor support

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image-tiff#89]
Forked from #70 .

The horizontal predictor for floating points does not use float differences, as those would be lossy, but apparently uses an integer difference. Recheck this with the standard.

There is a dedicated floating point predictor which first re-orders some bytes: http://chriscox.org/TIFFTN3d1.pdf

**Comment by TomasKralCZ** [comment]
I got the floating point predictor working, will try to polish the code a bit and submit a PR.

Here's a little visualization of how it works: (note that differencing is done _before_ reordering)
![visual](https://user-images.githubusercontent.com/23663355/118938225-b62e3000-b94e-11eb-9cb2-ef7e7973113e.png)

I only implemented the f32 version. Libtiff supports 16, 24, 32 and 64 bit versions. We currently don't support 16 and 24 bit floating-point samples at all, so I won't implement that but it won't be hard to add later. 

I guess I could add code for 64-bit samples as well, but I sadly don't have any test images in that format. All of my test images were generated using Photoshop, which doesn't support saving 64-bit samples.
